#          ___      _   _           ___          __ _ _
#         | _ ) ___| |_| |_ ___ _ _| _ \_ _ ___ / _(_) |___ ___
#         | _ \/ -_)  _|  _/ -_) '_|  _/ '_/ _ \  _| | / -_|_-<
#         |___/\___|\__|\__\___|_| |_| |_| \___/_| |_|_\___/__/
#                           by AlonsoAliaga
#          https://www.spigotmc.org/resources/authors/281176/
#
#
#                       BetterProfiles 1.0-BETA
#     Updated translation to Russian by king5442
#     Обновил перевод на Русский язык: King5442 (discord king5442#3173)
#
Messages:
  No-permission: "&cУ вас недостаточно прав."
  View-command-no-permission: "&cНажмите ПКМ по игроку, чтобы открыть его профиль. Приобретите привилегию &a[RANK] &cчтобы использовать эту команду."
  #Сообщение которое отправляется игроку, если у него нет прав (при нажатии ПКМ). Напишите "none" чтобы не отправлять сообщение.
  View-interact-no-permission: "&cВы не можете просматривать профили игроков. Приобретите привилегию &a[RANK] &cчтобы просматривать профили."
  Reloaded: "&aНекоторые сообщения и опции были обновлены. Остальные могут потребовать перезагрузки сервера!"
  Invalid-player: "&cИгрок не в сети!"
  Disabled-world: "&cПрофили выключены в этом мире :("
  Please-reconnect: "&cЧто-то пошло не так! Переподключитесь."
  Please-reconnect-other: "&cЧто-то пошло не так! Попросите игрока переподключиться."
  Profile-disabled-command: "&cКоманда выключена! Нажмите ПКМ по игроку, чтобы открыть профиль!"
  Profile:
    Title: "&8Профиль: {PLAYER}"
    Profile-is-locked: "&cВы не можете просматривать профиль этого игрока."
  Toggle-profiles:
    No-permission: "&cУ вас недостаточно прав."
    Profiles-locked: "&cПрофили выключены! Теперь вы не сможете просматривать профиль игроков."
    Profiles-unlocked: "&aПрофили включены! Теперь вы можете просматривать профили игроков."
  Toggle-profile:
    No-permission: "&cУ вас недостаточно прав."
    Profile-locked: "&cПрофиль заблокирован! Игроки не смогут просматривать ваш профиль."
    Profile-unlocked: "&aПрофиль разблокирован! Игроки могут просматривать ваш профиль."
  Help:
    Admin:
    - "&6 /betterprofiles &f- &eПроверить свой профиль"
    - "&6 /betterprofiles view <player> &f- &eОткрыть профиль игрока"
    - "&6 /betterprofiles toggle <viewer/profile>&f- &eПереключение между просмотром/показом профилей"
    - "&6 /betterprofiles reload &f- &eReload configuration"
    User:
    - "&6 /betterprofiles &f- &eCheck your profile"
    - "&6 /betterprofiles view <player> &f- &eCheck player's profile"
    - "&6 /betterprofiles toggle <viewer/profile>&f- &eToggle viewing/showing profiles"

Items:
  No-main-hand:
    #В случае, если вы используете собственный текстур-пак. (ТОЛЬКО 1.14+)
    #Установите значение 0, если вы не знаете, что это такое.
    Custom-model-data: 0
    Custom-model-data-hidden: 0
    Displayname: "&eОсновная рука"
    #Разрешите просмотреть этот слот. Установить "none", чтобы не требовать разрешения
    Permission: "none"
    Lore:
    - "&cПусто"
    Lore-hidden:
    - "&cВы не имеет прав, для просмотра этого слота."
  No-off-hand:
    Custom-model-data: 0
    Custom-model-data-hidden: 0
    Displayname: "&eВторая рука"
    Permission: "none"
    Lore:
    - "&cПусто"
    Lore-hidden:
    - "&cВы не имеет прав, для просмотра этого слота."
  No-helmet:
    Custom-model-data: 0
    Custom-model-data-hidden: 0
    Displayname: "&eШлем"
    Permission: "none"
    Lore:
    - "&cПусто"
    Lore-hidden:
    - "&cВы не имеет прав, для просмотра этого слота."
  No-chestplate:
    Custom-model-data: 0
    Custom-model-data-hidden: 0
    Displayname: "&eНагрудник"
    Permission: "none"
    Lore:
    - "&cПусто"
    Lore-hidden:
    - "&cВы не имеет прав, для просмотра этого слота."
  No-leggings:
    Custom-model-data: 0
    Custom-model-data-hidden: 0
    Displayname: "&eПоножи"
    Permission: "none"
    Lore:
    - "&cПусто"
    Lore-hidden:
    - "&cВы не имеет прав, для просмотра этого слота."
  No-boots:
    Custom-model-data: 0
    Custom-model-data-hidden: 0
    Displayname: "&eБотинки"
    Permission: "none"
    Lore:
    - "&cПусто"
    Lore-hidden:
    - "&cВы не имеет прав, для просмотра этого слота."
  Close:
    Custom-model-data: 0
    Displayname: "&cЗакрыть"
    Lore: []

Options:
   #Эта опция для 1.9+ серверов.
   #Это отменяет открытие профилей, если игрок держит щит в основной или во второй руке.
  Prevent-shield: true
   #Это отменяет открытие профилей, если игрок держит щит в основной или во второй руке.
  Prevent-interact: true
    #Включение этой функции открывает профиль только при нажатии ПКМ + Shift.
  Only-sneak: false
   #Если плагин включен, он попытается обновить инвентарь, если игрок обновит расположение предметов в инвентаре.
   #Включает в себя основную руку и вторую руку, если таковая имеется. Вам потребуется перезагрузить сервер для того чтобы она заработала.
  Update-equipment: true
   #Заполните все пустые слоты пользовательским элементом рамки. Не поддерживается название и описание.
   #Рамки - панели из стекла.
  Fill-empty:
    Enabled: true
   #Заполните все пустые слоты пользовательским элементом рамки. Не поддерживается название и описание.
   #Рамки - панели из стекла.
    Custom-model-data: 0
    #ЭТО ОТНОСИТСЯ КО ВСЕМ ИСПОЛЬЗУЕМЫМ ПРЕДМЕТАМ.
    #Доступные цвета: WHITE, ORANGE, MAGENTA, LIGHT_BLUE, YELLOW, LIME, PINK, GRAY, LIGHT_GRAY, CYAN, PURPLE, BLUE, BROWN, GREEN, RED, BLACK
    Color-frame: WHITE
  Empty-slot:
    #ЭТО ОТНОСИТСЯ КО ВСЕМ ПРЕДМЕТАМ, ИСПОЛЬЗУЕМЫМ, ЕСЛИ СЛОТ ИГРОКА ПУСТ.
    #Доступные цвета: WHITE, ORANGE, MAGENTA, LIGHT_BLUE, YELLOW, LIME, PINK, GRAY, LIGHT_GRAY, CYAN, PURPLE, BLUE, BROWN, GREEN, RED, BLACK
    Color-frame: YELLOW
  Hidden-slot:
    #ЭТО ОТНОСИТСЯ КО ВСЕМ СЛОТАМ, КОТОРЫЕ НЕ ВИДНЫ ИГРОКУ..
    Color-frame: RED
   #Эта функция отправит сообщение в поле "неверный игрок", если игрок, выполняющий
   #действие / команда не может видеть модель игрока. (Совместимо с плагинами на невидимость)
  Check-visibility: true
  Slots:
    Close: 49
    Helmet: 10
    Chestplate: 19
    Leggings: 28
    Boots: 37
    Main-hand: 20
    Off-hand: 29
  View:
    #Если значение true, то профили можно открыть, щелкнув правой кнопкой мыши по игроку. (true - включено, false - выключено)
    Interact: true
    #Если значение true, то профили можно открыть с помощью команды. (true - включено, false - выключено)
    Command: true
  #Миры, в которых профиль не открывается при щелчке правой кнопкой мыши или использовании команды.
  #Это не влияет на игроков с правами администратора.
  Disabled-worlds:
  - "world_pvp"
  #Установите значение "none", чтобы отключить звуковые эффекты..
  Sounds:
    #Звук при открытии профиля игрока.
    Open: "CHEST_OPEN"
    #Звук при закрытии профиля игрока.
    Close: "CHEST_CLOSE"

Permissions:
  Admin: "betterprofiles.admin"
  #Разрешение (права) на просмотр профилей с помощью щелчка правой кнопкой мыши.
  #Установите значение "none", чтобы убрать.
  View-interact: "none"
  #Разрешение на просмотр профилей с помощью команды /betterprofiles view <Игрок>
  #Установите значение "none", чтобы убрать.
  View-command: "betterprofiles.view.command"
  #Разрешение на запрет просмотра профиля других игроков.
  #Включить / отключить просмотр чужих профилей. Установите значение "none", чтобы убрать
  Toggle-view-profiles: "none" #Пример: "betterprofiles.toggle.others-profiles"
  #Разрешение на переключение просмотра профиля. Другие игроки могут / не могут видеть ваш профиль.
  #Включить / отключить просмотр своего профиля. Установите значение "none", чтобы убрать.
  Toggle-profile: "betterprofiles.toggle.profile"
  Bypass: "betterprofiles.view.bypass"
  #Полный доступ к просмотру профилей. Вы сможете открыть профиль игрока, даже если он запретил это делать. (Подойдёт для модераторов)
  Own-profile: "none" #Пример: "betterprofiles.view.myprofile"
  #Установите значение "none", чтобы убрать.

Database:
  #Доступные типы: MySQL и SQLite
  #Вы можете использовать MySQL, чтобы сделать его глобальным, или SQLite, чтобы сделать его локальным.
  #MySQL требует наличия сервера (локального или внешнего)
  #SQLite ничего не требует, он сохраняется в файле базы данных в папке.
  Type: "SQLite"
  Table: "betterprofiles"
  #If type is SQLite
  File: "database-betterprofiles"
  #If type is MySQL
  Host: 127.0.0.1
  Port: 3306
  Database: "betterprofiles"
  Username: "root"
  Password: "12345"

Updates:
  #Автоматическое обновление конфигурации? Включение приведет к удалению комментариев.
  Auto-update-configuration: true
  #Проверить наличие обновлений? Рекомендуется не выключать.
  Check-updates: true
  #Уведомлять об обновлениях, когда игрок с правами подключается к серверу?
  Notify-updates: true
  #Разрешение, необходимое для получения сообщения об обновлении плагина.
  Permission: "betterprofiles.update"
  #Сообщение при наличии обновления.
  Message: "&3[BetterProfiles] &eНайдено обновление! Вы используете версию {CURRENT}. Установите версию {NEW} здесь &c{LINK}"
